import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen`}
      >
        {/* Inline script to remove common extension-added attributes before React hydration
            Extensions like Grammarly sometimes add data-* attributes on the client which
            cause hydration mismatches. This script attempts to remove those attributes
            early to avoid React complaining during development. */}
        <script dangerouslySetInnerHTML={{ __html: `(() => {
          try {
            const attrs = ['data-new-gr-c-s-check-loaded', 'data-gr-ext-installed', 'data-gramm'];
            attrs.forEach(a => {
              if (document?.body?.hasAttribute(a)) document.body.removeAttribute(a);
              if (document?.documentElement?.hasAttribute(a)) document.documentElement.removeAttribute(a);
            });
            // remove any attribute starting with data-gr or data-gramm if present
            Array.from(document?.body?.attributes || []).forEach(att => {
              if (att && /^data-gr(amm)?/i.test(att.name)) document.body.removeAttribute(att.name);
            });
          } catch (e) { /* ignore */ }
        })();` }} />

        {children}
      </body>
    </html>
  );
}
